// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqptljfrcrhlkwlbnqel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxcHRsamZyY3JobGt3bGJucWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0NjU3ODEsImV4cCI6MjA1MzA0MTc4MX0.-whvbnTz4XGhZitWBTBC5EsLRI4nVqVfW6AQXwnYXc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);