// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqzyavuwubffnmwjjfqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxenlhdnV3dWJmZm5td2pqZnFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0MzUyNjIsImV4cCI6MjA1MjAxMTI2Mn0.WXj0YwnT9h0LMgYiZxHy1PbZ_2UzjVRrp_p_V0Rrd6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);