// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckdlxftpbsuevogncotw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrZGx4ZnRwYnN1ZXZvZ25jb3R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5ODQ5MTYsImV4cCI6MjA1MDU2MDkxNn0.IFNDyP6tdkbYoeRv6SJ9jeC6pdMHvjPwfrxohBpZFPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);